### ISSUE TITLE
sell token?

### ISSUE THREAD

**Issue by montedev0516** [montedev0516/Solana-Raydium-Sniper-bot#31]
sell token?

**Comment by driveForward0516** [comment]
export const tokenSell = async () => {
  console.log("starting token sell");
  /**
   * fetch sell siganls from database.
   */
  const buySolanaHistoryData: any = await getSolanaBuys();
  console.log("buySolanaHistoryData => ", buySolanaHistoryData);

  if (buySolanaHistoryData.length > 0) {
    let sellSolanaSignals: signal[] = [];
    /**
     * fetch valid EVM sell signals from EVM sell signal group. 
     */
    if (buySolanaHistoryData.length > 0) sellSolanaSignals = await convertAsSignal(buySolanaHistoryData, true);
    
    /**
     * configure all valid sell signals.
     */
    const sellSignals = [ ...sellSolanaSignals];
    console.log("sellSignals", sellSignals);
    if (sellSignals.length > 0) {
      for (let i = 0; i < sellSignals.length; i++) {
        try {
          await runTrade(sellSignals[i], i);
        }
        catch (e) {
          console.error("sell error", e);
        }
      }
      /**
       * Update successful sell signals in database.
       */
      if (sellActions.length > 0) {
        const res = await updateSells();
        console.log(res);
        sellActions.length = 0;
        startRouter(bot).sellEnd();

      }
    }
  }
}

**Comment by montedev0516** [comment]
thanks
